=== kurtharriger/spring-osgi/rfc-124/api/src/main/resources/blueprint.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
    /*
    * $Revision: 6534 $
    *
    * Copyright (c) OSGi Alliance (2008, 2009). All Rights Reserved.
    *
    * Licensed under the Apache License, Version 2.0 (the "License");
    * you may not use this file except in compliance with the License.
    * You may obtain a copy of the License at
    *
    *      http://www.apache.org/licenses/LICENSE-2.0
    *
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
    */
    -->
<xsd:schema xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.osgi.org/xmlns/blueprint/v1.0.0"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.0.0">

    <!-- Schema elements for core component declarations -->

    <xsd:complexType name="Tidentified" abstract="true">
        <xsd:attribute name="id" type="xsd:ID"/>
    </xsd:complexType>

    <xsd:element name="components" type="Tcomponents"/>

    <xsd:complexType name="Tcomponents">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:element name="type-converters" type="Ttype-converters" minOccurs="0"/>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="component" type="Tcomponent"/>
                <xsd:element name="ref-list" type="TreferenceCollection"/>
                <xsd:element name="ref-set" type="TreferenceCollection"/>
                <xsd:element name="reference" type="Treference"/>
                <xsd:element name="service" type="Tservice"/>
                <xsd:any namespace="##other" processContents="strict" minOccurs="0"
                         maxOccurs="unbounded"/>
            </xsd:choice>
        </xsd:sequence>
        <!--<xsd:attributeGroup ref="defaults"/>-->
        <xsd:attribute name="default-lazy-init" default="false" type="xsd:boolean"/>
        <xsd:attribute name="default-init-method" type="xsd:string"/>
        <xsd:attribute name="default-destroy-method" type="xsd:string"/>
        <xsd:attribute name="default-timeout" type="xsd:long" default="300000"/>
        <xsd:attribute name="default-availability" type="Tavailability" default="mandatory"/>
        <xsd:anyAttribute namespace="##other" processContents="lax"/>
    </xsd:complexType>

    <!--<xsd:element name="description" type="Tdescription"/>-->

    <xsd:complexType name="Tdescription" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded"/>
    </xsd:complexType>

    <!--<xsd:element name="type-converters" type="Ttype-converters"/>-->

    <xsd:complexType name="Ttype-converters">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="component" type="Tcomponent"/>
            <xsd:element name="ref" type="Tref"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:group name="componentElements">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="constructor-arg" type="Tconstructor-arg"/>
                <xsd:element name="property" type="Tproperty"/>
                <xsd:any namespace="##other" processContents="strict" minOccurs="0"
                         maxOccurs="unbounded"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:group>

    <xsd:complexType name="Tcomponent">
        <xsd:complexContent>
            <xsd:extension base="Tidentified">
                <xsd:group ref="componentElements"/>
                <xsd:attribute name="class" type="xsd:string"/>
                <xsd:attribute name="scope" type="xsd:string"/>
                <xsd:attribute name="lazy-init" default="default" type="Tdefaultable-boolean"/>
                <xsd:attribute name="depends-on" type="xsd:string"/>
                <xsd:attribute name="init-method" type="xsd:string"/>
                <xsd:attribute name="destroy-method" type="xsd:string"/>
                <xsd:attribute name="factory-method" type="xsd:string"/>
                <xsd:attribute name="factory-component" type="xsd:string"/>
                <xsd:anyAttribute namespace="##other" processContents="lax"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:group name="valueElement">
        <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="component" type="Tcomponent"/>
                <xsd:element name="ref" type="Tref"/>
                <xsd:element name="idref" type="Tref"/>
                <xsd:element name="value" type="Tvalue"/>
                <xsd:element name="null" type="Tnull"/>
                <xsd:element name="list" type="TlistSetArray"/>
                <xsd:element name="set" type="TlistSetArray"/>
                <xsd:element name="map" type="Tmap"/>
                <xsd:element name="array" type="TlistSetArray"/>
                <xsd:element name="props" type="Tprops"/>
                <xsd:element name="ref-list" type="TreferenceCollection"/>
                <xsd:element name="ref-set" type="TreferenceCollection"/>
                <xsd:element name="reference" type="Treference"/>
                <xsd:element name="service" type="Tservice"/>
                <xsd:any namespace="##other" processContents="strict"
                         minOccurs="0" maxOccurs="unbounded"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:group>

    <xsd:group name="keyElement">
        <xsd:sequence>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="component" type="Tcomponent"/>
                <xsd:element name="ref" type="Tref"/>
                <xsd:element name="idref" type="Tref"/>
                <xsd:element name="value" type="Tvalue"/>
                <xsd:element name="list" type="TlistSetArray"/>
                <xsd:element name="set" type="TlistSetArray"/>
                <xsd:element name="map" type="Tmap"/>
                <xsd:element name="array" type="TlistSetArray"/>
                <xsd:element name="props" type="Tprops"/>
                <xsd:element name="ref-list" type="TreferenceCollection"/>
                <xsd:element name="ref-set" type="TreferenceCollection"/>
                <xsd:element name="reference" type="Treference"/>
                <xsd:element name="service" type="Tservice"/>
                <xsd:any namespace="##other" processContents="strict"
                         minOccurs="0" maxOccurs="unbounded"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:group>


    <!--<xsd:element name="constructor-arg" type="Tconstructor-arg"/>-->

    <xsd:complexType name="Tconstructor-arg">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:group ref="valueElement"/>
        </xsd:sequence>
        <xsd:attribute name="index" type="xsd:int"/>
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="ref" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="property" type="Tproperty"/>

    <!--<xsd:element name="ref" type="Tref"/>-->

    <xsd:complexType name="Tref">
        <xsd:complexContent>
            <xsd:restriction base="xsd:anyType">
                <xsd:attribute name="component" type="xsd:string" use="required"/>
            </xsd:restriction>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="Tvalue" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded"/>
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="Tnull" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded"/>
    </xsd:complexType>

    <xsd:complexType name="Tkey">
        <xsd:group ref="keyElement"/>
    </xsd:complexType>

    <xsd:complexType name="Tprop" mixed="true">
        <xsd:attribute name="key" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="Tproperty">
        <xsd:sequence>
            <xsd:element name="description" type="Tdescription" minOccurs="0"/>
            <xsd:group ref="valueElement"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="ref" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>

    <!-- Collection Types -->

    <!-- base collection type -->
    <xsd:complexType name="TbaseCollection"/>

    <!-- base type for collections that have (possibly) typed nested values -->
    <xsd:complexType name="TtypedCollection">
        <xsd:complexContent>
            <xsd:extension base="TbaseCollection">
                <xsd:attribute name="value-type" type="xsd:string"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!-- 'map' element type -->
    <xsd:complexType name="Tmap">
        <xsd:complexContent>
            <xsd:extension base="TtypedCollection">
                <xsd:sequence>
                    <xsd:element name="entry" type="Tentry" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:attribute name="key-type" type="xsd:string"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!-- 'entry' element type -->
    <xsd:complexType name="Tentry">
        <xsd:sequence>
            <xsd:element name="key" type="Tkey" minOccurs="0"/>
            <xsd:group ref="valueElement"/>
        </xsd:sequence>
        <xsd:attribute name="key" type="xsd:string"/>
        <xsd:attribute name="key-ref" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
        <xsd:attribute name="value-ref" type="xsd:string"/>
    </xsd:complexType>

    <!-- 'list' and 'set' collection type -->
    <xsd:complexType name="TlistSetArray">
        <xsd:complexContent>
            <xsd:extension base="TtypedCollection">
                <xsd:group ref="valueElement" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!-- 'props' collection type -->
    <xsd:complexType name="Tprops">
        <xsd:complexContent>
            <xsd:extension base="TbaseCollection">
                <xsd:sequence>
                    <xsd:element name="prop" type="Tprop" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!-- simple internal types -->
    <xsd:simpleType name="Tdefaultable-boolean">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:enumeration value="default"/>
            <xsd:enumeration value="true"/>
            <xsd:enumeration value="false"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Treference">
        <xsd:complexContent>
            <xsd:extension base="Tidentified">
                <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                    <xsd:element name="interfaces" type="TlistSetArray" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="listener" type="Tlistener" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:attribute name="interface" use="optional" type="xsd:token"/>
                <xsd:attribute name="filter" use="optional" type="xsd:string"/>
                <xsd:attribute name="component-name" type="xsd:string" use="optional"/>
                <xsd:attribute name="availability" use="optional" type="Tavailability" default="mandatory"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:complexType name="Tlistener">
        <xsd:choice>
            <xsd:element name="ref" type="Tref"/>
            <xsd:element name="component" type="Tcomponent"/>
            <xsd:element name="reference" type="Treference"/>
            <xsd:element name="service" type="Tservice"/>
            <!-- nested component declaration -->
            <xsd:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="lax"/>
        </xsd:choice>

        <!-- shortcut for component references -->
        <xsd:attribute name="ref" type="xsd:string" use="optional"/>
        <xsd:attribute name="bind-method" type="xsd:token" use="required"/>
        <xsd:attribute name="unbind-method" type="xsd:token" use="required"/>
    </xsd:complexType>

    <!-- single reference -->
    <xsd:complexType name="TsingleReference">
        <xsd:complexContent>
            <xsd:extension base="Treference">
                <xsd:attribute name="timeout" use="optional" type="xsd:long"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:simpleType name="Tavailability">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="mandatory"/>
            <xsd:enumeration value="optional"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="TreferenceCollection">
        <xsd:complexContent>
            <xsd:extension base="Treference">
                <xsd:sequence minOccurs="0" maxOccurs="1">
                    <xsd:element name="comparator" type="Tcomparator"/>
                </xsd:sequence>
                <xsd:attribute name="comparator-ref" type="xsd:string" use="optional"/>
                <xsd:attribute name="member-type" type="Tmember" use="optional"/>
                <xsd:attribute name="ordering-basis" type="TorderingBasis" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:simpleType name="Tmember">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="service-instance"/>
            <xsd:enumeration value="service-reference"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Tcomparator">
        <xsd:choice>
            <xsd:element name="ref" type="Tref"/>
            <xsd:element name="component" type="Tcomponent"/>
            <xsd:element name="reference" type="Treference"/>
            <xsd:element name="service" type="Tservice"/>
            <!-- nested component declaration -->
            <xsd:any namespace="##other" minOccurs="1" maxOccurs="1" processContents="lax"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:simpleType name="TorderingBasis">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="service"/>
            <xsd:enumeration value="service-reference"/>
        </xsd:restriction>
    </xsd:simpleType>


    <!-- service -->

    <xsd:complexType name="Tservice">
        <xsd:complexContent>
            <xsd:extension base="Tidentified">
                <xsd:choice>
                    <xsd:group ref="serviceElements"/>
                    <!-- nested component declaration -->
                    <xsd:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="lax"/>
                </xsd:choice>
                <xsd:attribute name="interface" type="xsd:token" use="optional"/>
                <xsd:attribute name="ref" type="xsd:string" use="optional"/>
                <xsd:attribute name="depends-on" type="xsd:string" use="optional"/>
                <xsd:attribute name="auto-export" type="TautoExportModes" default="disabled"/>
                <xsd:attribute name="ranking" type="xsd:int" default="0"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:group name="serviceElements">
        <xsd:sequence>
            <xsd:element name="interfaces" type="TlistSetArray" minOccurs="0"/>
            <xsd:element name="service-properties" type="Tmap" minOccurs="0"/>
            <xsd:element name="registration-listener" type="TserviceRegistrationListener"
                         minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="component" type="Tcomponent" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:group>

    <xsd:complexType name="TserviceRegistrationListener">
        <xsd:choice>
            <xsd:element name="ref" type="Tref"/>
            <xsd:element name="component" type="Tcomponent"/>
            <xsd:element name="reference" type="Treference"/>
            <xsd:element name="service" type="Tservice"/>
            <xsd:any namespace="##other" minOccurs="0" maxOccurs="1" processContents="lax"/>
        </xsd:choice>

        <!-- shortcut for component references -->
        <xsd:attribute name="ref" type="xsd:string" use="optional"/>
        <xsd:attribute name="registration-method" type="xsd:token" use="required"/>
        <xsd:attribute name="unregistration-method" type="xsd:token" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="TautoExportModes">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="disabled"/>
            <xsd:enumeration value="interfaces"/>
            <xsd:enumeration value="class-hierarchy"/>
            <xsd:enumeration value="all-classes"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== kurtharriger/spring-osgi/rfc-124/core/src/test/resources/org/springframework/osgi/blueprint/config/type-converters.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:beans="http://www.springframework.org/schema/beans"
	xsi:schemaLocation="
		http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd
		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">


	<description>Type converters config</description>

	<type-converters>
		<component
			class="org.springframework.osgi.blueprint.config.TestComponentConverter" />
		<ref component="converterB" />
	</type-converters>

	<component id="converterB"
		class="org.springframework.osgi.blueprint.config.ComponentHolderConverter" />

	<component id="conversion" class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<value type="org.springframework.osgi.blueprint.TestComponent">sergey</value> 
		</property>
		<property name="propB">
			<value type="org.springframework.osgi.blueprint.config.ComponentHolder">rachmaninoff</value> 
		</property>
	</component>
</components>

=== kurtharriger/spring-osgi/rfc-124/ri/core/src/test/resources/org/springframework/osgi/blueprint/config/component-subelements.xml
<?xml version="1.0" encoding="UTF-8"?>

<components xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd"
	default-init-method="init">

	<description>Configuration with sub-elements</description>


	<component id="char" class="java.lang.Character">
		<constructor-arg type="char" value="\u0000"/>
	</component>
	
	<component id="constructor-arg" class="java.lang.Integer">
		<description>description</description>
		<constructor-arg index="0" type="int" value="3" />
	</component>

	<component id="constructor-arg-ref" class="java.lang.String">
		<description>description2</description>
		<constructor-arg ref="constructor-arg" />
	</component>

	<component id="propertyValueInline" class="java.net.Socket">
		<property name="keepAlive" value="false" />
	</component>

	<component id="propertyValueRef" class="java.net.Socket">
		<property name="sendBufferSize" ref="constructor-arg" />
	</component>

	<component id="idref" class="java.lang.String">
		<constructor-arg>
			<idref component="constructor-arg" />
		</constructor-arg>
	</component>

	<component id="propertyValueNested" class="java.net.Socket">
		<property name="sendBufferSize">
			<component class="java.lang.Integer">
				<constructor-arg value="3" />
			</component>
		</property>
	</component>

	<component id="list"
		class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<description>ignored</description>
			<list>
				<value type="java.lang.String">value</value>
				<idref component="idref" />
				<null />
				<ref component="idref" />
			</list>
		</property>
	</component>

	<component id="listWDefaultType"
		class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<description>ignored</description>
			<list value-type="java.lang.Double">
                <value>0.0</value>
                <value>1.0</value>
			</list>
		</property>
	</component>

	<component id="set"
		class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<description>ignored</description>
			<set>
				<value type="java.lang.String">value</value>
				<idref component="idref" />
				<null />
				<ref component="idref" />
			</set>
		</property>

	</component>

	<component id="map"
		class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<map>
				<entry key="foo" value="bar" />
				<entry key-ref="list" value-ref="set" />
				<entry>
					<key><ref component="set"/></key>
					<ref component="list"/>
				</entry>
			</map>
		</property>
	</component>

	<component id="props"
		class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<props>
				<prop key="one">two</prop>
				<prop key="aero">smith</prop>
			</props>
		</property>
	</component>

	<component id="null" 
		class="org.springframework.osgi.blueprint.TestComponent">
		<property name="propA">
			<null/>
		</property>
	</component>
	
	<component id="compZeroLengthString" class="org.springframework.osgi.blueprint.TestComponent">
       <property name="propA" value=""/>
    </component> 
   
    <!-- 
	<component id="dateConstructor"
	 	class="org.springframework.osgi.blueprint.DateConstructor">
	 	<constructor-arg value="6/1/1999" type="java.util.Date"/> 
	</component>
	--> 
	
	<component id="nan" factory-method="valueOf" class="java.lang.Double">
       <constructor-arg value="NaN" type="double"/>
    </component>
    
    <component id="ambigousConstructor" class="org.springframework.osgi.blueprint.AmbigousTestComponent">
       <constructor-arg type="java.lang.String" value="compThreeArgOverride"/>
       <constructor-arg  type="java.lang.Object" value="true">
       </constructor-arg>
       <constructor-arg type="java.lang.String"><null/></constructor-arg>
    </component>
   
    <component id="nestedArgs" class="java.lang.Boolean">
	   <constructor-arg type="java.lang.String">
	   		<value type="java.lang.Boolean">true</value>
	   </constructor-arg>
	</component>

    <component id="nestedArgs2" class="java.lang.Boolean">
	   <constructor-arg type="boolean">
	   		<value>true</value>
	   </constructor-arg>
	</component>
    
    <component id="staticFactory" factory-method="staticMethod" class="org.springframework.osgi.blueprint.FactoryComponent">
       <constructor-arg value="String" index="1"/>
       <constructor-arg value="123" index="2"/>
       <constructor-arg value="981" index="0"/>
    </component>
   
</components>

=== kurtharriger/spring-osgi/rfc-124/ri/core/src/test/resources/org/springframework/osgi/blueprint/config/importer-elements.xml
<?xml version="1.0" encoding="UTF-8"?>

<components xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

	<description>Importer configuration</description>

	<component id="listener"
		class="org.springframework.osgi.blueprint.ImporterListener" />

	<reference id="simple" interface="java.lang.Cloneable" />

	<reference id="options" interface="java.io.Serializable"
		availability="optional" component-name="foo" filter="(name=foo)">
		<listener bind-method="bind" unbind-method="unbind" ref="listener"/>
	</reference>

	<reference id="multipleInterfaces">
		<interfaces>
			<value>java.lang.Cloneable</value>
			<value>java.io.Serializable</value>
		</interfaces>
	</reference>

</components>

=== kurtharriger/spring-osgi/rfc-124/ri/core/src/test/resources/org/springframework/osgi/blueprint/config/basic-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd"
		default-init-method="init">

	<description>Components just with attributes</description>

	<component id="simple" class="java.lang.Object"/>
	
	<component id="depends-on" class="java.lang.Object" depends-on="simple"/>
	
	<component id="destroy-method" class="java.util.Properties" destroy-method="clear"/>

	<component id="lazy-init" class="java.lang.Object" lazy-init="true"/>
	
	<component id="factory-method" class="java.lang.System" factory-method="currentTimeMillis"/>
	
	<component id="thread" class="java.lang.Thread"/>
	
	<component id="factory-component" factory-component="thread" factory-method="getName"/>
	
</components>

=== kurtharriger/spring-osgi/rfc-124/ri/core/src/test/resources/org/springframework/osgi/blueprint/config/exporter-elements.xml
<?xml version="1.0" encoding="UTF-8"?>

<components xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

	<description>Exporter configuration</description>


	<component id="listener"
		class="org.springframework.osgi.blueprint.ExporterListener" />

	<component id="map" class="java.util.LinkedHashMap" />

	<service id="simple" ref="map" interface="java.util.Map"
		ranking="123">
		<service-properties>
			<entry key="fat" value="lip" />
			<entry key="mountain" value="song" />
		</service-properties>
	</service>

	<service id="nested" auto-export="all-classes">
		<interfaces>
			<value>java.util.Map</value>
			<value>java.io.Serializable</value>
		</interfaces>

		<registration-listener registration-method="up"
			unregistration-method="down">
			<ref component="listener" />
		</registration-listener>

		<registration-listener registration-method="up"
			unregistration-method="down">
			<component
				class="org.springframework.osgi.blueprint.ExporterListener" />
		</registration-listener>

		<component class="java.util.LinkedHashMap" />
	</service>
</components>

=== kurtharriger/spring-osgi/rfc-124/ri/core/src/test/resources/org/springframework/osgi/blueprint/config/nested-elements.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd"
	default-init-method="init">

	<description>Components mixed subelements</description>

	<component id="classname" class="java.lang.String">
		<constructor-arg value="java.io.Serializable" />
	</component>

	<component id="class" factory-method="forName"
		class="java.lang.Class">
		<constructor-arg value="java.lang.Cloneable" />
	</component>

	<reference id="foo">
		<interfaces>
			<ref component="classname" />
			<ref component="class" />
		</interfaces>
	</reference>
	
	<reference id="bar">
		<interfaces>
			<ref component="classname" />
			<ref component="class" />
		</interfaces>
	</reference>
	

</components>
